210733fc-29b1-4154-9488-e064b51bf83c:
  current_animation: 1
  current_block: 1
  ExtraShort:
    tries: 115
    completed_rounds: 14
    highscore: '2.2940'
bbda4232-6000-4a9c-898d-9447e76c0a9b:
  current_animation: 1
  current_block: 2
  ExtraShort:
    tries: 39
    completed_rounds: 17
    highscore: '0.0040'
1e071c5c-f2e0-40d6-8f20-beb01caabd4b:
  current_animation: 3
  current_block: 1
  ExtraShort:
    tries: 54
    completed_rounds: 4
    highscore: '4.3990'
