block-menu-category {
    blocks=[
        WOOL,
        "DIAMOND_BLOCK",
        "GOLD_BLOCK",
        "IRON_BLOCK",
        "REDSTONE_BLOCK",
        "LAPIS_BLOCK",
        "QUARTZ_BLOCK"
    ]
    "default_block"=WOOL
}
general-category {
    # This will set the default island category when they're not provided upon creation
    default-island-category=standard
    # The space gap between islands
    island-space-gap=10
    # Useful when debugging
    show-debug-message=false
}
leaderboard-category {
    # A leaderboard will update on every x interval. It's defined in seconds.
    global-update-interval=60
    # The leaderboard's format.
    leaderboard-format="&e%position%. &6%name% &7(%score%)"
    # A session leaderboard will update on every x interval. It's defined in seconds.
    session-update-interval=10
}
lobby-category {
    # This is where the players will teleport when they join, or leave an island
    lobby-location {
        pitch=0.03675342723727226
        world=world
        x=6.5
        y=7.0
        yaw=179.96910095214844
        z=641.5
    }
    # If this is set to true, the players will teleport to the lobby upon them joining
    teleport-on-join=true
}
